services:
  moodtracker-api:
    container_name: moodtracker-api
    hostname: moodtracker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - moodtracker-network
    env_file: .env.prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  moodtracker-network:
    driver: bridge