services:
  moodtracker-api-dev:
    container_name: moodtracker-api-dev
    hostname: moodtracker-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    networks:
      - moodtracker-network-dev
    env_file: .env.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      moodtracker-db:
        condition: service_healthy

  moodtracker-db:
    image: postgres:15-alpine
    container_name: moodtracker-db
    hostname: moodtracker-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moodtracker-network-dev
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:

networks:
  moodtracker-network-dev:
    driver: bridge